### PR TITLE
Updated webcomponent + changed logo and favicon (b&w version)

### PR DESCRIPTION
**Pull request by madeincima**

### CODE REVIEW

**Comment by Piiit** [comment]
@madeincima This PR has conflicts, please resolve them

**Comment by madeincima** [comment]
@Piiit hi, this can be resolved by just replacing my commited file "src/js/webcomponent/noi_maps_widget.min.js" (is the new builded js)

**Comment by Piiit** [comment]
@madeincima I know, please do this... I have many PRs, so I need to get them without conflicts and errors... Sorry about the inconvenience.

**Comment by Piiit** [comment]
@madeincima Cherry picked and merged via command line... since we use the CDN to get the noi_maps_widget.min.js file, we no longer need it... I will add it to .gitignore... if you want it for local development, just copy/paste your version into that folder, but we will never push it back to the repo... thanks

**Comment by Piiit** [comment]
Test version can be seen at https://maps.noi.testingmachine.eu/

**Comment by madeincima** [comment]
Hello Peter, thank you so much for your help here and on the webcomp-maps-noi repo! :)

The only strange thing I see is that on https://maps.noi.testingmachine.eu/ everything is fine but the planimetries are not up to date For example https://github.com/noi-techpark/webcomp-maps-noi/blob/development/resources/planimetry/a1-0.svg this planimetry is new the one ( I can see the new "Meeting Room Steve (bookable for the NOI-Community) - A1-0-35-A" ) but on the website is visibile the old one ( e.g. https://maps.noi.testingmachine.eu/en/?shared=A1-0-35&lang=en  )

**Comment by Piiit** [comment]
@madeincima I checked and found out, that we have only a production server for new images... I will create a new server which contains the new testing images... 

Production = https://images.maps.noi.opendatahub.bz.it
Staging = https://images.maps.noi.opendatahub.testingmachine.eu

...with the same folder structure... Now I need to update the web component to understand that

**Comment by Piiit** [comment]
@madeincima please check the Planimetrie again... thanks

**Pull request closed without merging**
